# Site settings
title: Strapyll # replace this with your own
author: Mash Software # replace this with your own
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
theme: bootstrap


# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
